// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { BeatNFTMarketplace$Type } from "./BeatNFTMarketplace";
import { IERC721$Type } from "./IERC721";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["BeatNFTMarketplace"]: BeatNFTMarketplace$Type;
    ["IERC721"]: IERC721$Type;
    ["contracts/BeatNFTMarketplace.sol:BeatNFTMarketplace"]: BeatNFTMarketplace$Type;
    ["contracts/BeatNFTMarketplace.sol:IERC721"]: IERC721$Type;
  }

  interface ContractTypesMap {
    ["BeatNFTMarketplace"]: GetContractReturnType<BeatNFTMarketplace$Type["abi"]>;
    ["IERC721"]: GetContractReturnType<IERC721$Type["abi"]>;
    ["contracts/BeatNFTMarketplace.sol:BeatNFTMarketplace"]: GetContractReturnType<BeatNFTMarketplace$Type["abi"]>;
    ["contracts/BeatNFTMarketplace.sol:IERC721"]: GetContractReturnType<IERC721$Type["abi"]>;
  }
}
