// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { BeatNFTCreditSystemV2$Type } from "./BeatNFTCreditSystemV2";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["BeatNFTCreditSystemV2"]: BeatNFTCreditSystemV2$Type;
    ["contracts/BeatNFTCreditSystemV2.sol:BeatNFTCreditSystemV2"]: BeatNFTCreditSystemV2$Type;
  }

  interface ContractTypesMap {
    ["BeatNFTCreditSystemV2"]: GetContractReturnType<BeatNFTCreditSystemV2$Type["abi"]>;
    ["contracts/BeatNFTCreditSystemV2.sol:BeatNFTCreditSystemV2"]: GetContractReturnType<BeatNFTCreditSystemV2$Type["abi"]>;
  }
}
