#!/bin/bash

echo "🔥 Firebase Firestore Manual Seeding Instructions"
echo "=================================================="
echo ""
echo "1. Login to Firebase CLI:"
echo "   firebase login"
echo ""
echo "2. Set project:"
echo "   firebase use beatswap-36c32"
echo ""
echo "3. Open Firestore in browser:"
echo "   firebase open firestore"
echo ""
echo "4. OR use these curl commands to seed via REST API:"
echo ""

# Get Firebase project info
PROJECT_ID="beatswap-36c32"
echo "# Seed Users Collection"
echo "curl -X POST \\"
echo "  'https://firestore.googleapis.com/v1/projects/$PROJECT_ID/databases/(default)/documents/users' \\"
echo "  -H 'Authorization: Bearer \$(gcloud auth print-access-token)' \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{"
echo "    \"fields\": {"
echo "      \"uid\": {\"stringValue\": \"user-1\"},"
echo "      \"email\": {\"stringValue\": \"beatmaster@beatschain.app\"},"
echo "      \"displayName\": {\"stringValue\": \"Beat Master\"},"
echo "      \"role\": {\"stringValue\": \"producer\"},"
echo "      \"isVerified\": {\"booleanValue\": true},"
echo "      \"createdAt\": {\"timestampValue\": \"2024-01-01T00:00:00Z\"}"
echo "    }"
echo "  }'"
echo ""

echo "# Seed Beats Collection"
echo "curl -X POST \\"
echo "  'https://firestore.googleapis.com/v1/projects/$PROJECT_ID/databases/(default)/documents/beats' \\"
echo "  -H 'Authorization: Bearer \$(gcloud auth print-access-token)' \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{"
echo "    \"fields\": {"
echo "      \"id\": {\"stringValue\": \"beat-1\"},"
echo "      \"title\": {\"stringValue\": \"Amapiano Fire\"},"
echo "      \"producerId\": {\"stringValue\": \"user-1\"},"
echo "      \"price\": {\"doubleValue\": 299.99},"
echo "      \"genre\": {\"stringValue\": \"amapiano\"},"
echo "      \"bpm\": {\"integerValue\": \"112\"},"
echo "      \"key\": {\"stringValue\": \"C minor\"},"
echo "      \"isNFT\": {\"booleanValue\": false},"
echo "      \"createdAt\": {\"timestampValue\": \"2024-01-15T00:00:00Z\"}"
echo "    }"
echo "  }'"
echo ""

echo "# Seed Producer Stats Collection"
echo "curl -X POST \\"
echo "  'https://firestore.googleapis.com/v1/projects/$PROJECT_ID/databases/(default)/documents/producer-stats' \\"
echo "  -H 'Authorization: Bearer \$(gcloud auth print-access-token)' \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{"
echo "    \"fields\": {"
echo "      \"totalEarnings\": {\"doubleValue\": 2450.75},"
echo "      \"totalSales\": {\"integerValue\": \"12\"},"
echo "      \"totalPlays\": {\"integerValue\": \"1847\"},"
echo "      \"updatedAt\": {\"timestampValue\": \"2024-01-15T00:00:00Z\"}"
echo "    }"
echo "  }'"
echo ""

echo "5. After seeding, test the API:"
echo "   curl http://localhost:3000/api/beats"
echo ""
echo "6. Check dashboard data:"
echo "   curl http://localhost:3000/api/producer/stats?producerId=user-1"