// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { CreatorLicensing$Type } from "./CreatorLicensing";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["CreatorLicensing"]: CreatorLicensing$Type;
    ["contracts/CreatorLicensing.sol:CreatorLicensing"]: CreatorLicensing$Type;
  }

  interface ContractTypesMap {
    ["CreatorLicensing"]: GetContractReturnType<CreatorLicensing$Type["abi"]>;
    ["contracts/CreatorLicensing.sol:CreatorLicensing"]: GetContractReturnType<CreatorLicensing$Type["abi"]>;
  }
}
