// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { BeatNFTCreditSystem$Type } from "./BeatNFTCreditSystem";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["BeatNFTCreditSystem"]: BeatNFTCreditSystem$Type;
    ["contracts/BeatNFTCreditSystem.sol:BeatNFTCreditSystem"]: BeatNFTCreditSystem$Type;
  }

  interface ContractTypesMap {
    ["BeatNFTCreditSystem"]: GetContractReturnType<BeatNFTCreditSystem$Type["abi"]>;
    ["contracts/BeatNFTCreditSystem.sol:BeatNFTCreditSystem"]: GetContractReturnType<BeatNFTCreditSystem$Type["abi"]>;
  }
}
