// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IERC721Metadata$Type } from "./IERC721Metadata";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IERC721Metadata"]: IERC721Metadata$Type;
    ["@openzeppelin/contracts/token/ERC721/extensions/IERC721Metadata.sol:IERC721Metadata"]: IERC721Metadata$Type;
  }

  interface ContractTypesMap {
    ["IERC721Metadata"]: GetContractReturnType<IERC721Metadata$Type["abi"]>;
    ["@openzeppelin/contracts/token/ERC721/extensions/IERC721Metadata.sol:IERC721Metadata"]: GetContractReturnType<IERC721Metadata$Type["abi"]>;
  }
}
