// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { NexthFT$Type } from "./NexthFT";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["NexthFT"]: NexthFT$Type;
    ["contracts/NFT.sol:NexthFT"]: NexthFT$Type;
  }

  interface ContractTypesMap {
    ["NexthFT"]: GetContractReturnType<NexthFT$Type["abi"]>;
    ["contracts/NFT.sol:NexthFT"]: GetContractReturnType<NexthFT$Type["abi"]>;
  }
}
