// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { BeatMarketplace$Type } from "./BeatMarketplace";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["BeatMarketplace"]: BeatMarketplace$Type;
    ["contracts/BeatMarketplace.sol:BeatMarketplace"]: BeatMarketplace$Type;
  }

  interface ContractTypesMap {
    ["BeatMarketplace"]: GetContractReturnType<BeatMarketplace$Type["abi"]>;
    ["contracts/BeatMarketplace.sol:BeatMarketplace"]: GetContractReturnType<BeatMarketplace$Type["abi"]>;
  }
}
