// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { IERC4906$Type } from "./IERC4906";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["IERC4906"]: IERC4906$Type;
    ["@openzeppelin/contracts/interfaces/IERC4906.sol:IERC4906"]: IERC4906$Type;
  }

  interface ContractTypesMap {
    ["IERC4906"]: GetContractReturnType<IERC4906$Type["abi"]>;
    ["@openzeppelin/contracts/interfaces/IERC4906.sol:IERC4906"]: GetContractReturnType<IERC4906$Type["abi"]>;
  }
}
