// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ERC721URIStorage$Type } from "./ERC721URIStorage";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ERC721URIStorage"]: ERC721URIStorage$Type;
    ["@openzeppelin/contracts/token/ERC721/extensions/ERC721URIStorage.sol:ERC721URIStorage"]: ERC721URIStorage$Type;
  }

  interface ContractTypesMap {
    ["ERC721URIStorage"]: GetContractReturnType<ERC721URIStorage$Type["abi"]>;
    ["@openzeppelin/contracts/token/ERC721/extensions/ERC721URIStorage.sol:ERC721URIStorage"]: GetContractReturnType<ERC721URIStorage$Type["abi"]>;
  }
}
