// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { BeatNFT$Type } from "./BeatNFT";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["BeatNFT"]: BeatNFT$Type;
    ["contracts/BeatNFT.sol:BeatNFT"]: BeatNFT$Type;
  }

  interface ContractTypesMap {
    ["BeatNFT"]: GetContractReturnType<BeatNFT$Type["abi"]>;
    ["contracts/BeatNFT.sol:BeatNFT"]: GetContractReturnType<BeatNFT$Type["abi"]>;
  }
}
